name: Purge jsDelivr Cache

on:
  push:
    branches:
      - main

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr cache
        run: |
          curl -X GET "https://purge.jsdelivr.net/gh/LaneMelancon/crawford-kajabi-styles@main/styles.css"
